### ISSUE TITLE
64 bit?

### ISSUE THREAD

**Issue by tujoworker** [smclab/TiDAKeyboardControl#6]
Would be great to get this module in 64 bit :)

**Comment by yuchi** [comment]
For sure before xmas :christmas_tree:

**Comment by tujoworker** [comment]
I just say WOW.

**Comment by bcpi** [comment]
+1 for this. Currently updating our app for 64 bit and would love to have this module 64-bit ready. Thanks!

**Comment by yuchi** [comment]
Can I suggest you to watch this repository? I’ll tag the new version and you’ll be notified.

Also in the meanwhile you can also stargaze it :P

**Comment by yuchi** [comment]
[See 0.4.0 :gift:](https://github.com/smclab/TiDAKeyboardControl/releases/tag/0.4.0)
